/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Symbol kind for VSCode DocumentSymbol */
export const enum SymbolKind {
  Module = 'Module',
  Interface = 'Interface',
  Package = 'Package',
  Class = 'Class',
  Task = 'Task',
  Function = 'Function',
  Parameter = 'Parameter',
  Port = 'Port',
  Variable = 'Variable',
  Net = 'Net',
  Instance = 'Instance',
  Typedef = 'Typedef',
  Enum = 'Enum',
  Struct = 'Struct',
  Property = 'Property',
  Sequence = 'Sequence',
  Covergroup = 'Covergroup'
}
/** A symbol extracted from SV source */
export interface SvSymbol {
  name: string
  kind: SymbolKind
  detail?: string
  startLine: number
  startCol: number
  endLine: number
  endCol: number
  children: Array<SvSymbol>
}
/** Parse result */
export interface ParseResult {
  symbols: Array<SvSymbol>
  errors: Array<string>
}
export interface FormatOptions {
  nbSpace?: number
  useTab?: boolean
  oneBindPerLine?: boolean
  oneDeclPerLine?: boolean
  paramOneLine?: boolean
  indentStyle?: string
  reindentOnly?: boolean
  stripEmptyLine?: boolean
  instAlignPort?: boolean
  ignoreTick?: boolean
  importSameLine?: boolean
  alignComma?: boolean
  maxConsecutiveEmptyLines?: number
}
export interface GadgetOptions {
  instPrefix?: string
  reset?: Array<string>
  sreset?: Array<string>
  clock?: Array<string>
  waveType?: string
  taskInit?: boolean
  taskDrive?: boolean
  includeDeclarations?: boolean
}
export interface RepeatOptions {
  start?: number
  end?: number
  rowStep?: number
  colStep?: number
  clipboardLines?: Array<string>
}
export interface ModuleInstResult {
  success: boolean
  result?: string
  module?: string
  error?: string
}
export interface TestbenchResult {
  success: boolean
  result?: string
  module?: string
  error?: string
}
/** Format Verilog/SystemVerilog text. */
export declare function formatText(text: string, options: FormatOptions): string
/** Generate module instantiation code. */
export declare function generateModuleInst(text: string, options: GadgetOptions): ModuleInstResult
/** Generate testbench code. */
export declare function generateTestbench(text: string, options: GadgetOptions): TestbenchResult
/** Repeat code with number formatting. */
export declare function repeatCode(template: string, options: RepeatOptions): string
/** Align selected Verilog code. */
export declare function alignCode(text: string, tabSize: number): string
/** Generate file header from template. */
export declare function generateHeader(template: string, fileName: string, tabSize: number): string
/** Extract all symbols from SystemVerilog source (for Outline / DocumentSymbol). */
export declare function extractSymbols(text: string): ParseResult
/** Find symbols by name (for hover / goto definition). */
export declare function findSymbolByName(text: string, name: string): Array<SvSymbol>
